### ISSUE TITLE
Check for mismatch between package.json version and CHANGELOG.md version

### ISSUE THREAD

**Issue by sam3d** [sam3d/changelog#15]
Currently if the `package.json` says the version is `2.0.3` and the earliest CHANGELOG.md version is `0.4.5`, it will update both the `package.json` and the CHANGELOG.md to `0.4.6` (assuming the version is a `patch`).

This is unintended behaviour and could cause problems.

**Comment by cwhitby** [comment]
What is the correct behaviour here?
Fail all, update `CHANGELOG.md` or update `package.json`?

**Comment by samholmes1337** [comment]
What I had in mind was perhaps using something like 'inquirer' to ask the user to choose between one or the other?
